// <auto-generated />
using System;
using Infrastructure.Data.ApplicaionDbContetxt;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241006114024_AddSeadedDataForUsersAndCategories")]
    partial class AddSeadedDataForUsersAndCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Domain.Models.Banner", b =>
                {
                    b.Property<Guid>("BannerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BannerId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Banner");
                });

            modelBuilder.Entity("Domain.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("b710d26f-369b-46c3-b133-2e4e522d5530"),
                            CategoryName = "Category 1"
                        },
                        new
                        {
                            CategoryId = new Guid("8c0c0bf0-7dea-4aad-9628-d768a1744355"),
                            CategoryName = "Category 2"
                        },
                        new
                        {
                            CategoryId = new Guid("fc2e27bd-5551-4b41-9699-e7a4dc367532"),
                            CategoryName = "Category 3"
                        },
                        new
                        {
                            CategoryId = new Guid("3bb92864-b902-4e89-8b97-d049b0b6178a"),
                            CategoryName = "Category 4"
                        });
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("0371098e-898d-45ca-84b2-42790a7ab1c3"),
                            FullName = "Name 1"
                        },
                        new
                        {
                            UserId = new Guid("fb7b0b35-baf2-4718-9bbf-a9ab6206224b"),
                            FullName = "Name 2"
                        },
                        new
                        {
                            UserId = new Guid("243991d2-65dd-4636-868c-1f8f48ab8475"),
                            FullName = "Name 3"
                        },
                        new
                        {
                            UserId = new Guid("4ce8ca07-8f81-4312-93d6-828d336af05b"),
                            FullName = "Name 4"
                        });
                });

            modelBuilder.Entity("Domain.Models.Banner", b =>
                {
                    b.HasOne("Domain.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Owner");
                });
#pragma warning restore 612, 618
        }
    }
}
